### ISSUE TITLE
How can I change icon color based on Hover Active etc pseudo-classes ?

### ISSUE THREAD

**Issue by outlawshade** [gorangajic/react-icons#60]
I mean is there anyway to set component class because className='' isn;t working with me

**Comment by kumarharsh** [comment]
Yes, I'm doing it myself.

```css
.icon {
  color: blue;
}
.icon:hover {
  color: red;
}
```

```jsx
render() {
  ...
  return (
    <div className={css.icon}>  {/* using css-modules */}
      <FaStar />
    </div>
  )
}
```
